M48
; DRILL file {KiCad 7.0.9} date Mon Jan 29 19:21:26 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-29T19:21:26-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.645Y-5.6
X2.695Y-3.7
X4.695Y-4.3
X4.695Y-5.4
X5.645Y-3.7
X5.895Y-5.6
T0
M30
